allowBuilds:
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@4.1.10'
  - '@vitest/expect@4.1.10'
  - '@vitest/mocker@4.1.10'
  - '@vitest/pretty-format@4.1.10'
  - '@vitest/runner@4.1.10'
  - '@vitest/snapshot@4.1.10'
  - '@vitest/spy@4.1.10'
  - '@vitest/utils@4.1.10'
  - vitest@4.1.10
overrides:
  serialize-javascript: ^7.0.5
  "@babel/core": ^7.29.6
  "@babel/plugin-transform-modules-systemjs": ^7.29.4
  fast-uri: ^3.1.2
  esbuild: ^0.28.1
