name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up toolchain
        uses: ./.github/actions/setup-node-pnpm

      - name: Verify app
        run: pnpm check

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=tide

      - name: Print deployment URL
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
          DEPLOYMENT_ALIAS_URL: ${{ steps.deploy.outputs.pages-deployment-alias-url }}
        run: |
          echo "Deployment URL: ${DEPLOYMENT_URL}"
          echo "Deployment alias URL: ${DEPLOYMENT_ALIAS_URL}"
